### ISSUE TITLE
Emote: wave

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#2953]
As mentioned in https://github.com/slowtorta/turtlewow-bug-tracker/issues/1985#issuecomment-1223813161, /wave makes a sound when it shouldn't. See my linked comment.
I'm opening a new issue as the previous one was closed.

**Comment by slowtorta** [comment]
Fixed in 1.16.6

**Comment by cyaohiri** [comment]
The issue persists in the new client (1.17.0).

**Comment by twowTurtReynolds** [comment]
Yep sure can do, I'll be testing this later.

**Comment by twowTurtReynolds** [comment]
I talked with Torta, it looks like this was a misunderstanding. The sounds added to /wave /greet /roar and others were intentional Turtle WoW changes.

**Comment by cyaohiri** [comment]
Oh, I see. The one for /greet is okay, but /wave is used a lot for saying goodbye, I still see people using it for that, though the character says "Hello!", so that seemed off.

**Comment by twowTurtReynolds** [comment]
Good point actually, we both agree. We'll aim for it to make it into 1.17.1

**Comment by cyaohiri** [comment]
Thank you!

**Comment by slowtorta** [comment]
Fixed in 1.7.1
