### ISSUE TITLE
Mage: Arcane Missiles animation

### ISSUE THREAD

**Issue by Basmong** [slowtorta/turtlewow-bug-tracker#951]
Mage Arcane Missiles have really bad animation. 

First, the mob is damaged, and then the animation of the first missile is displayed. 
The last missile is displayed when the spell has already been completed and the character has dropped his hands!

I've tested this with different spell ranks and with two different races. 

One guy already mentioned this on forum half a year ago. Watch the video.  https://forum.turtle-wow.org/viewtopic.php?f=3&t=1136

spell: https://database.turtle-wow.org/?spell=5143

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by geojak** [comment]
@slowtorta hello torta, arcance missiles rank 1 still shots the last third missile after the spell has already finished.
first missil after 50% channeling, second missile after 100% channelng, thrid missile somewhile after

not fixed

**Comment by slowtorta** [comment]
> @slowtorta hello torta, arcance missiles rank 1 still shots the last third missile after the spell has already finished. first missil after 50% channeling, second missile after 100% channelng, thrid missile somewhile after
> 
> not fixed

Can't reproduce, working alright on my end.

**Comment by geojak** [comment]
i asked in world chat for other magesto test and they also say not fixed

**Comment by geojak** [comment]
https://www.youtube.com/watch?v=n3ujzPWNUW8
at sec 30 in this video you can see how arcane missiles rank 1 should look like.

if i see this correctly, the first missile should immidielty shot

**Comment by geojak** [comment]
on t wow rank 1 arcane missiles shot one missile each at
50% channeling, 100% channeling, 150%(??) channling

on classic wow it shots at 33% 66% 100%

**Comment by OonaQueenoftheBae** [comment]
Playlist showing taken on 5/25
In addition to  the animation being janky. I also sometimes don't get all of the missiles as showing in the First Video (Lose out on 1 missile) and the last clip (Lose out on 2 missiles)

https://youtube.com/playlist?list=PLoJjOcE78CJtCui1NQgR8HRA6l-puFmn0

**Comment by geojak** [comment]
https://m.youtube.com/playlist?list=PLoJjOcE78CJtCui1NQgR8HRA6l-puFmn0
Someone on mage guild discord made a hole playlisr with comments on the still bugged arcane missiles animations
Pls reopen
